### ISSUE TITLE
About the difference between DCFST-18 tracker file and DCFST-50 tracker file

### ISSUE THREAD

**Issue by botaoye** [CASIA-IVA-Lab/DCFST#3]
Hi author, thanks for your wonderful work. As you mentioned in the ReadMe, there are two different tracker files for DCFST-18 and DCFST-50 separately, but it seems that the only difference between  DCFST-18 and DCFST-50 should only be the network layer number. So, 1) why two different tracker files are necessary? 2) what's the main differences between two tracker files? 3)can I use tracker file of DCFST-50 to track DCFST-18 model and get similar performance with the reported results in paper?

Thank you very much!

**Comment by noneUmbrella** [comment]
Thank you for your attention！In fact, there is no essential difference between the two tracker files. The most direct reason for the two versions is to catch up with the deadline of VOT2019, we wrote a rough version in a short time, that is DCFST-18 file. Later, in order to better show our method in the submited paper, we re-optimized part of the implementation details of DCFST-18 tracker to make it more efficient and part of the details more reasonable, then DCFST-50 file came up. You can test any tracker file with any backbone. We just provide DCFST-18 file to reproduce the result of the paper perfectly. In fact, DCFST-50 is recommended.

**Comment by botaoye** [comment]
> Thank you for your attention！In fact, there is no essential difference between the two tracker files. The most direct reason for the two versions is to catch up with the deadline of VOT2019, we wrote a rough version in a short time, that is DCFST-18 file. Later, in order to better show our method in the submited paper, we re-optimized part of the implementation details of DCFST-18 tracker to make it more efficient and part of the details more reasonable, then DCFST-50 file came up. You can test any tracker file with any backbone. We just provide DCFST-18 file to reproduce the result of the paper perfectly. In fact, DCFST-50 is recommended.

I got it! Thanks for your reply.
